In [1]:
import re

In [4]:
para = """  <p>Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. <strong>AI-powered systems</strong> are widely used in healthcare, finance, and education.</p>
            <p>Modern applications often leverage <em>machine learning</em> and <u>deep learning</u> techniques to process large amounts of data efficiently.</p>
            <p>To learn more about AI concepts, visit <a href="https://www.example.com">this resource</a> and review the <code>Python</code> examples provided.</p> """

In [5]:
para

'  <p>Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. <strong>AI-powered systems</strong> are widely used in healthcare, finance, and education.</p>\n            <p>Modern applications often leverage <em>machine learning</em> and <u>deep learning</u> techniques to process large amounts of data efficiently.</p>\n            <p>To learn more about AI concepts, visit <a href="https://www.example.com">this resource</a> and review the <code>Python</code> examples provided.</p> '

### Using Regular Expression

In [6]:
re.findall("<.+?>", para)

['<p>',
 '<strong>',
 '</strong>',
 '</p>',
 '<p>',
 '<em>',
 '</em>',
 '<u>',
 '</u>',
 '</p>',
 '<p>',
 '<a href="https://www.example.com">',
 '</a>',
 '<code>',
 '</code>',
 '</p>']

In [7]:
re.sub("<.+?>","",para)

'  Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. AI-powered systems are widely used in healthcare, finance, and education.\n            Modern applications often leverage machine learning and deep learning techniques to process large amounts of data efficiently.\n            To learn more about AI concepts, visit this resource and review the Python examples provided. '

### Beautiful Soup

In [8]:
!pip install -q bs4

In [9]:
from bs4 import BeautifulSoup

In [10]:
para

'  <p>Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. <strong>AI-powered systems</strong> are widely used in healthcare, finance, and education.</p>\n            <p>Modern applications often leverage <em>machine learning</em> and <u>deep learning</u> techniques to process large amounts of data efficiently.</p>\n            <p>To learn more about AI concepts, visit <a href="https://www.example.com">this resource</a> and review the <code>Python</code> examples provided.</p> '

In [11]:
bs_para = BeautifulSoup(para, "html.parser")

In [12]:
bs_para

 <p>Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. <strong>AI-powered systems</strong> are widely used in healthcare, finance, and education.</p>
<p>Modern applications often leverage <em>machine learning</em> and <u>deep learning</u> techniques to process large amounts of data efficiently.</p>
<p>To learn more about AI concepts, visit <a href="https://www.example.com">this resource</a> and review the <code>Python</code> examples provided.</p>

In [13]:
type(para)

str

In [14]:
type(bs_para)

bs4.BeautifulSoup

In [15]:
bs_para.get_text()

' Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. AI-powered systems are widely used in healthcare, finance, and education.\nModern applications often leverage machine learning and deep learning techniques to process large amounts of data efficiently.\nTo learn more about AI concepts, visit this resource and review the Python examples provided. '

### Removing HTML Tags from Dataset

In [16]:
import pandas as pd

In [17]:
import numpy as np

In [18]:
dfmovie =pd.read_csv("D:\DATASETS\Classification-Datasets\IMDB.csv")

In [19]:
dfmovie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [21]:
dfmovie.head(1)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive

In [22]:
dfmovie["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [23]:
dfmovie["review"][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [24]:
dfmovie["review"][2]

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [25]:
dfmovie["review"]

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [26]:
dfmovie["review"].map( lambda x : re.sub("<.+?>", "", x) )

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [27]:
dfmovie["review"] = dfmovie["review"].map( lambda x : re.sub("<.+?>", "", x) )

In [28]:
dfmovie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [29]:
dfmovie["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [30]:
dfmovie["review"][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [31]:
mystr = "Python Pythons Snake Python Horse Pythons Cat Python"

In [32]:
re.findall("Python", mystr)

['Python', 'Python', 'Python', 'Python', 'Python']

In [33]:
re.findall("Pythons", mystr)

['Pythons', 'Pythons']

In [35]:
re.findall("Pythons?", mystr)

['Python', 'Pythons', 'Python', 'Pythons', 'Python']

In [36]:
para

'  <p>Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. <strong>AI-powered systems</strong> are widely used in healthcare, finance, and education.</p>\n            <p>Modern applications often leverage <em>machine learning</em> and <u>deep learning</u> techniques to process large amounts of data efficiently.</p>\n            <p>To learn more about AI concepts, visit <a href="https://www.example.com">this resource</a> and review the <code>Python</code> examples provided.</p> '

In [39]:
re.findall("<.+>",para)

['<p>Artificial Intelligence is transforming industries by enabling machines to learn and make decisions. <strong>AI-powered systems</strong> are widely used in healthcare, finance, and education.</p>',
 '<p>Modern applications often leverage <em>machine learning</em> and <u>deep learning</u> techniques to process large amounts of data efficiently.</p>',
 '<p>To learn more about AI concepts, visit <a href="https://www.example.com">this resource</a> and review the <code>Python</code> examples provided.</p>']

In [41]:
re.findall("<.+?>",para)

['<p>',
 '<strong>',
 '</strong>',
 '</p>',
 '<p>',
 '<em>',
 '</em>',
 '<u>',
 '</u>',
 '</p>',
 '<p>',
 '<a href="https://www.example.com">',
 '</a>',
 '<code>',
 '</code>',
 '</p>']

###  URL Removal

In [42]:
"www.google.com"
"https://www.kaggle.com/"
"http://www.kaggle.com/"
"https://kaggle.com/"
"http://kaggle.com/"

'http://kaggle.com/'

In [44]:
sent1 = "Visit google www.google.com for performing intense web search and also vist google mail www.gmail.com for mailing server."

In [45]:
sent1

'Visit google www.google.com for performing intense web search and also vist google mail www.gmail.com for mailing server.'

In [46]:
re.findall("www.\S+", sent1)

['www.google.com', 'www.gmail.com']

In [52]:
sent2 = "Kaggle https://www.kaggle.com/ is popular http://kaggle.com/ online repository http://www.kaggle.com/ for datasets."

In [53]:
re.findall("https:\S+", sent2)

['https://www.kaggle.com/']

In [54]:
re.findall("https?:\S+", sent2)

['https://www.kaggle.com/', 'http://kaggle.com/', 'http://www.kaggle.com/']

In [ ]:
sent2 = "Kaggle https://www.kaggle.com/ is popular #  http://kaggle.com/ online @ repository http://www.kaggle.com/ for datasets."