In [4]:
import pandas as pd

In [5]:
import numpy as np

### Case Folding

In [1]:
sent1 = "Hello ALL, Very GOOD MORNING... Welcome to NLP class"

In [2]:
sent1.lower()

'hello all, very good morning... welcome to nlp class'

In [3]:
sent1.upper()

'HELLO ALL, VERY GOOD MORNING... WELCOME TO NLP CLASS'

In [6]:
dfmovie =pd.read_csv("D:\DATASETS\Classification-Datasets\IMDB.csv")

In [7]:
dfmovie.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
dfmovie["review"]

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [9]:
dfmovie["review"].map(lambda x : x.lower())

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [10]:
dfmovie["review"].map(lambda x : x.upper())

0        ONE OF THE OTHER REVIEWERS HAS MENTIONED THAT ...
1        A WONDERFUL LITTLE PRODUCTION. <BR /><BR />THE...
2        I THOUGHT THIS WAS A WONDERFUL WAY TO SPEND TI...
3        BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY ...
4        PETTER MATTEI'S "LOVE IN THE TIME OF MONEY" IS...
                               ...
49995    I THOUGHT THIS MOVIE DID A DOWN RIGHT GOOD JOB...
49996    BAD PLOT, BAD DIALOGUE, BAD ACTING, IDIOTIC DI...
49997    I AM A CATHOLIC TAUGHT IN PAROCHIAL ELEMENTARY...
49998    I'M GOING TO HAVE TO DISAGREE WITH THE PREVIOU...
49999    NO ONE EXPECTS THE STAR TREK MOVIES TO BE HIGH...
Name: review, Length: 50000, dtype: object

### Contractions

In [11]:
!pip install -q contractions

In [12]:
sent2 = """It's hard to believe that you completed the task. we've tried multiple ways but it didn't work.
            I'm a bit busy this weekend, please don't disturbe me as i can't append party"""

In [13]:
sent2

"It's hard to believe that you completed the task. we've tried multiple ways but it didn't work.\n            I'm a bit busy this weekend, please don't disturbe me as i can't append party"

In [14]:
import contractions

In [15]:
contractions.fix(sent2)

'It is hard to believe that you completed the task. we have tried multiple ways but it did not work.\n            I am a bit busy this weekend, please do not disturbe me as i cannot append party'

### Abbreviation

In [18]:
sent3 = """AI is a futuristic technology which inclues ML , DL along with computer vision and NLP. To execute CNN and RNN model we require 
            GPU processor."""

In [36]:
abbre = {
            "AI" : "Artificial Intelligence",
            "ML" : "Machine Learning",
            "DL" : "Deep Learning",
            "NLP" : "Natural Language Processing",
            "NLP." : "Natural Language Processing",
            "CNN" : "Convolutional Neural Network",
            "RNN" : "Recurrent Neural Network",
            "GPU" : "Graphical Processing Unit"
                    }

In [37]:
words = sent3.split()

In [38]:
words

['AI',
 'is',
 'a',
 'futuristic',
 'technology',
 'which',
 'inclues',
 'ML',
 ',',
 'DL',
 'along',
 'with',
 'computer',
 'vision',
 'and',
 'NLP.',
 'To',
 'execute',
 'CNN',
 'and',
 'RNN',
 'model',
 'we',
 'require',
 'GPU',
 'processor.']

In [39]:
import time

In [40]:
for w in words : 
    print(abbre.get(w, w))

Artificial Intelligence
is
a
futuristic
technology
which
inclues
Machine Learning
,
Deep Learning
along
with
computer
vision
and
Natural Language Processing
To
execute
Convolutional Neural Network
and
Recurrent Neural Network
model
we
require
Graphical Processing Unit
processor.

In [41]:
abbre.get("ak", "No Such Key")

'No Such Key'

In [42]:
[abbre.get(w, w)     for w in words]

['Artificial Intelligence',
 'is',
 'a',
 'futuristic',
 'technology',
 'which',
 'inclues',
 'Machine Learning',
 ',',
 'Deep Learning',
 'along',
 'with',
 'computer',
 'vision',
 'and',
 'Natural Language Processing',
 'To',
 'execute',
 'Convolutional Neural Network',
 'and',
 'Recurrent Neural Network',
 'model',
 'we',
 'require',
 'Graphical Processing Unit',
 'processor.']

In [43]:
" ".join([abbre.get(w, w)     for w in words])

'Artificial Intelligence is a futuristic technology which inclues Machine Learning , Deep Learning along with computer vision and Natural Language Processing To execute Convolutional Neural Network and Recurrent Neural Network model we require Graphical Processing Unit processor.'

### Punctuations

In [44]:
from string import punctuation

In [50]:
punc = punctuation

In [51]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [46]:
text = """Hello ALL..!, Welcome to "NLP" class."""

In [48]:
text

'Hello ALL..!, Welcome to "NLP" class.'

In [52]:
for i in text:
    if i not in punc: 
        print(i)

H
e
l
l
o

A
L
L

W
e
l
c
o
m
e

t
o

N
L
P

c
l
a
s
s

In [53]:
[ c  for c in text if c not in punc]

['H',
 'e',
 'l',
 'l',
 'o',
 ' ',
 'A',
 'L',
 'L',
 ' ',
 'W',
 'e',
 'l',
 'c',
 'o',
 'm',
 'e',
 ' ',
 't',
 'o',
 ' ',
 'N',
 'L',
 'P',
 ' ',
 'c',
 'l',
 'a',
 's',
 's']

In [54]:
"".join([ c  for c in text if c not in punc])

'Hello ALL Welcome to NLP class'

In [55]:
dfmovie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [57]:
import re

In [58]:
dfmovie["review"].map(lambda x : re.sub("<.+?>","", x))

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. The filming tec...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [59]:
dfmovie["review"] = dfmovie["review"].map(lambda x : re.sub("<.+?>","", x))

In [60]:
dfmovie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [61]:
dfmovie["review"].map(lambda x : "".join([c  for c in x if c not in punc]))

0        One of the other reviewers has mentioned that ...
1        A wonderful little production The filming tech...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [62]:
dfmovie["review"] = dfmovie["review"].map(lambda x : "".join([c  for c in x if c not in punc]))

In [63]:
dfmovie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production The filming tech...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically theres a family where a little boy J...  negative
4      Petter Matteis Love in the Time of Money is a ...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot bad dialogue bad acting idiotic direc...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  Im going to have to disagree with the previous...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

### Tokenization

In [64]:
!pip install -q nltk

In [65]:
import nltk

In [66]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [70]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [68]:
sent3

'AI is a futuristic technology which inclues ML , DL along with computer vision and NLP. To execute CNN and RNN model we require \n            GPU processor.'

In [69]:
word_tokenize(sent3)

['AI',
 'is',
 'a',
 'futuristic',
 'technology',
 'which',
 'inclues',
 'ML',
 ',',
 'DL',
 'along',
 'with',
 'computer',
 'vision',
 'and',
 'NLP',
 '.',
 'To',
 'execute',
 'CNN',
 'and',
 'RNN',
 'model',
 'we',
 'require',
 'GPU',
 'processor',
 '.']

In [71]:
sent3.split()

['AI',
 'is',
 'a',
 'futuristic',
 'technology',
 'which',
 'inclues',
 'ML',
 ',',
 'DL',
 'along',
 'with',
 'computer',
 'vision',
 'and',
 'NLP.',
 'To',
 'execute',
 'CNN',
 'and',
 'RNN',
 'model',
 'we',
 'require',
 'GPU',
 'processor.']

### Sent Tokenization

In [72]:
sent3

'AI is a futuristic technology which inclues ML , DL along with computer vision and NLP. To execute CNN and RNN model we require \n            GPU processor.'

In [73]:
sent_tokenize(sent3)

['AI is a futuristic technology which inclues ML , DL along with computer vision and NLP.',
 'To execute CNN and RNN model we require \n            GPU processor.']

### Stop Words

In [74]:
import nltk

In [75]:
from nltk.corpus import stopwords

In [76]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [77]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [78]:
sw_eng = stopwords.words("english")

In [79]:
sw_eng

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [80]:
dfmovie["review"][0]

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with meThe first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordIt is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayI would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [82]:
dfmovie["review"][0].split()

['One',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'Oz',
 'episode',
 'youll',
 'be',
 'hooked',
 'They',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'meThe',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'Oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'GO',
 'Trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'This',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'Its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'wordIt',
 'is',
 'called',
 'OZ',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 'It',
 'focuses',
 'mainly',
 'on',
 'Emerald',
 'City',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'Em',
 'City',
 'is',
 'home',
 'to',
 'manyAryans',
 'Muslims',
 'gangstas',
 'Latinos',
 'Christians',
 'Italians',
 'Irish',
 'and',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'awayI',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'wouldnt',
 'dare',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceOZ',
 'doesnt',
 'mess',
 'around',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'I',
 'couldnt',
 'say',
 'I',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'I',
 'watched',
 'more',
 'I',
 'developed',
 'a',
 'taste',
 'for',
 'Oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'Not',
 'just',
 'violence',
 'but',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 'Watching',
 'Oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewingthats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

In [81]:
len( dfmovie["review"][0].split() )

301

In [83]:
[w  for w in dfmovie["review"][0].split() if w not in sw_eng]

['One',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'Oz',
 'episode',
 'youll',
 'hooked',
 'They',
 'right',
 'exactly',
 'happened',
 'meThe',
 'first',
 'thing',
 'struck',
 'Oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 'set',
 'right',
 'word',
 'GO',
 'Trust',
 'show',
 'faint',
 'hearted',
 'timid',
 'This',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 'sex',
 'violence',
 'Its',
 'hardcore',
 'classic',
 'use',
 'wordIt',
 'called',
 'OZ',
 'nickname',
 'given',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 'It',
 'focuses',
 'mainly',
 'Emerald',
 'City',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 'privacy',
 'high',
 'agenda',
 'Em',
 'City',
 'home',
 'manyAryans',
 'Muslims',
 'gangstas',
 'Latinos',
 'Christians',
 'Italians',
 'Irish',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'shady',
 'agreements',
 'never',
 'far',
 'awayI',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'wouldnt',
 'dare',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceOZ',
 'doesnt',
 'mess',
 'around',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'I',
 'couldnt',
 'say',
 'I',
 'ready',
 'I',
 'watched',
 'I',
 'developed',
 'taste',
 'Oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'Not',
 'violence',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'sold',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'Watching',
 'Oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewingthats',
 'get',
 'touch',
 'darker',
 'side']

In [84]:
len([w  for w in dfmovie["review"][0].split() if w not in sw_eng])

179

In [85]:
301 - 179

122

In [86]:
" ".join([w  for w in dfmovie["review"][0].split() if w not in sw_eng])

'One reviewers mentioned watching 1 Oz episode youll hooked They right exactly happened meThe first thing struck Oz brutality unflinching scenes violence set right word GO Trust show faint hearted timid This show pulls punches regards drugs sex violence Its hardcore classic use wordIt called OZ nickname given Oswald Maximum Security State Penitentary It focuses mainly Emerald City experimental section prison cells glass fronts face inwards privacy high agenda Em City home manyAryans Muslims gangstas Latinos Christians Italians Irish moreso scuffles death stares dodgy dealings shady agreements never far awayI would say main appeal show due fact goes shows wouldnt dare Forget pretty pictures painted mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck nasty surreal I couldnt say I ready I watched I developed taste Oz got accustomed high levels graphic violence Not violence injustice crooked guards wholl sold nickel inmates wholl kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience Watching Oz may become comfortable uncomfortable viewingthats get touch darker side'

In [87]:
dfmovie["review"][0]

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with meThe first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordIt is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayI would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [88]:
dfmovie["review"].map(lambda x : " ".join([ w   for w in x.split() if w not in sw_eng]) )

0        One reviewers mentioned watching 1 Oz episode ...
1        A wonderful little production The filming tech...
2        I thought wonderful way spend time hot summer ...
3        Basically theres family little boy Jake thinks...
4        Petter Matteis Love Time Money visually stunni...
                               ...
49995    I thought movie right good job It wasnt creati...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I Catholic taught parochial elementary schools...
49998    Im going disagree previous comment side Maltin...
49999    No one expects Star Trek movies high art fans ...
Name: review, Length: 50000, dtype: object

### Stemming

In [90]:
# Write, writes, writing... ==> write
# code, codes, coding, coder.... ==> code 

# Change, Changing, Changes, Changer, changed ==> Chang

# Universe, universal, university, universities ==> univers

In [91]:
import nltk

In [92]:
from nltk.stem import PorterStemmer

In [93]:
pstem = PorterStemmer()

In [94]:
pstem.stem("writing")

'write'

In [95]:
pstem.stem("running")

'run'

In [96]:
pstem.stem("runner")

'runner'

In [97]:
pstem.stem("changing")

'chang'

In [98]:
pstem.stem("university")

'univers'